# Generated by Django 5.2.17 on 2026-09-20 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shared', models.BooleanField(default=False)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('node_ids', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reference')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('BRANCH', 'فرع'), ('SPEC', 'وصف'), ('ITEM', 'بند')], max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.referencenode')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.reference')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='DRAFT', max_length=12)),
                ('date', models.DateField()),
                ('reference_name', models.CharField(blank=True, max_length=200)),
                ('reference_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(default='DRAFT', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.visit')),
            ],
        ),
        migrations.CreateModel(
            name='VisitNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('node_type', models.CharField(max_length=20)),
                ('origin', models.CharField(default='MANUAL', max_length=20)),
                ('selected', models.BooleanField(default=True)),
                ('excluded', models.BooleanField(default=False)),
                ('completion_required', models.BooleanField(default=False)),
                ('scope_locked', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, max_length=20)),
                ('observation', models.TextField(blank=True)),
                ('parent_id_snapshot', models.CharField(blank=True, max_length=80)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.visit')),
            ],
        ),
    ]
