# Generated by Django 5.2.17 on 2026-09-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(max_length=80)),
                ('scope_locked', models.BooleanField(default=False)),
                ('completion_required', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.assignment')),
            ],
            options={
                'unique_together': {('assignment', 'stable_id')},
            },
        ),
    ]
