from django.db import models
from django.contrib.auth.models import User
class Institution(models.Model): name=models.CharField(max_length=200); kind=models.CharField(max_length=120,blank=True); active=models.BooleanField(default=True)
class Reference(models.Model): name=models.CharField(max_length=200); owner=models.ForeignKey(User,null=True,blank=True,on_delete=models.SET_NULL); shared=models.BooleanField(default=False); snapshot=models.JSONField(default=dict); created_at=models.DateTimeField(auto_now_add=True)
class ReferenceNode(models.Model): reference=models.ForeignKey(Reference,on_delete=models.CASCADE,related_name='nodes'); stable_id=models.CharField(max_length=80); title=models.CharField(max_length=255); node_type=models.CharField(max_length=20,choices=[('BRANCH','فرع'),('SPEC','وصف'),('ITEM','بند')]); parent=models.ForeignKey('self',null=True,blank=True,on_delete=models.CASCADE); position=models.PositiveIntegerField(default=0)
class ReferenceProposal(models.Model):
 reference=models.ForeignKey(Reference,on_delete=models.CASCADE,related_name='proposals'); submitter=models.ForeignKey(User,on_delete=models.PROTECT); snapshot=models.JSONField(default=dict); status=models.CharField(max_length=10,default='PENDING'); reviewed_by=models.ForeignKey(User,null=True,blank=True,on_delete=models.SET_NULL,related_name='reviewed_proposals'); reviewed_at=models.DateTimeField(null=True,blank=True)
class Guide(models.Model): name=models.CharField(max_length=200); reference=models.ForeignKey(Reference,on_delete=models.CASCADE); node_ids=models.JSONField(default=list); active=models.BooleanField(default=True)
class Visit(models.Model): DRAFT='DRAFT'; COMPLETED='COMPLETED'; status=models.CharField(max_length=12,default=DRAFT); institution=models.ForeignKey(Institution,on_delete=models.PROTECT); inspector=models.ForeignKey(User,on_delete=models.PROTECT); date=models.DateField(); reference_name=models.CharField(max_length=200,blank=True); reference_snapshot=models.JSONField(default=dict); created_at=models.DateTimeField(auto_now_add=True)
class VisitNode(models.Model): visit=models.ForeignKey(Visit,on_delete=models.CASCADE,related_name='items'); stable_id=models.CharField(max_length=80); title=models.CharField(max_length=255); node_type=models.CharField(max_length=20); origin=models.CharField(max_length=20,default='MANUAL'); selected=models.BooleanField(default=True); excluded=models.BooleanField(default=False); completion_required=models.BooleanField(default=False); scope_locked=models.BooleanField(default=False); result=models.CharField(max_length=20,blank=True); observation=models.TextField(blank=True); parent_id_snapshot=models.CharField(max_length=80,blank=True)
class Assignment(models.Model):
 visit=models.ForeignKey(Visit,on_delete=models.CASCADE,related_name='assignments'); title=models.CharField(max_length=200); status=models.CharField(max_length=10,default='DRAFT'); reason=models.TextField(blank=True); issued_at=models.DateTimeField(null=True,blank=True); revoked_at=models.DateTimeField(null=True,blank=True)
class AssignmentEntry(models.Model):
 assignment=models.ForeignKey(Assignment,on_delete=models.CASCADE,related_name='entries'); stable_id=models.CharField(max_length=80); scope_locked=models.BooleanField(default=False); completion_required=models.BooleanField(default=False)
 class Meta: unique_together=('assignment','stable_id')
